### ISSUE TITLE
feat: Problem with new version of docarray

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#47] opened 2022-04-04 09:51 UTC
When using latest version of docarray, we get following error on calling `da = da.shuffle(seed=42)`. This needs to be investigated and then the concern should be raised with `docarray` team, if it is an upstream problem.
![image](https://user-images.githubusercontent.com/6537525/161519633-babb9966-888c-4520-9078-e6933a9f91d2.png)

**Comment by davidbp** [comment] 2022-04-04 10:08
Seems could be a bug from the recent updates on id2offset . Could you provide a MWE with a toy `da` to reproduce this?

**Comment by davidbp** [comment] 2022-04-04 10:45
After debugging this we can see that the error is because the sample mechanism now expects `da._data` to be a list, and in this example is a `dict` (since the object was serialized using an older docarray version). Updating it to the new version should solve this.

**Comment by makram93** [comment] 2022-04-04 11:04
Thanks for your input @davidbp. As discussed with @florian-hoenicke, we will set the docarray version for now. We will re-create our dataset file with `protobuf` serialisation technique but later

**Comment by davidbp** [comment] 2022-04-04 11:19
Sure, recall that you can specify as extension of the docarray the protocol and compression methods used https://docarray.jina.ai/fundamentals/documentarray/serialization/  this will avoid the frustration of not being able to load back from bytes when you don't remember how you stored them in the first place.

**Comment by slettner** [comment] 2022-06-08 15:38
This is closed by https://github.com/jina-ai/now/pull/240

**Closed by slettner** 2022-06-08 15:38 UTC
