### ISSUE TITLE
bug: scores rounded incorrectly?

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#1085] opened 2023-02-16 12:35 UTC
There seem to be problems in rounding the scores. I would expect that the search results are constant when one score is 0 even if I modify the other one. Why does a weight of 0.21 give a different result if it is the only score?

[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://user-images.githubusercontent.com/11627845/219345930-249ec98a-307f-4e2e-905e-24690c02f3b7.mov)

**Comment by IyadhKhalfallah** [comment] 2023-03-01 14:52
After investigating this issue, these are the conclusions taken:
- The playground is working as expected
- The bff is working as expected
- There might be an elasticsearch issue when storing the semantic scores
- This might be due to the fact that the images have the same scores (eliminated because it's nearly impossible)
The issue couldn't be reproduced. Thus, we are closing this for now.

**Closed by IyadhKhalfallah** 2023-03-01 14:52 UTC
